export type ModelType =
    "bow_own_tiny"
    | "bow_own_small"
    | "bow_own_medium"
    | "bow_own_large"
    | "bow_own_huge"
    | "bertolt_small"
    | "bertolt_large"
    | "bertrand_small"
    | "bertrand_large"
    | "mask_baseline_small"
    | "mask_baseline_large"
    | "custom_transformer_small"
    | "custom_transformer_medium"
    | "custom_transformer_large"
    | "fasttext_library"
    | "mbert"
    | "bow_bpemb_s"
    | "bow_bpemb_m"
    | "bow_fasttext"
    | "bow_bigrams"
    | "bow_trigrams"
    | "bow_fourgrams"
    | "bow_fivegrams";
